// Packages the built game (dist/) into expo/game-html.ts as one
// self-contained HTML string for the WebView. Run via `npm run build:expo`.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";

const asset = readdirSync("dist/assets").find((f) => f.endsWith(".js"));
if (!asset) throw new Error("dist/assets has no JS bundle — run vite build first");
const js = readFileSync(`dist/assets/${asset}`, "utf8");

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, user-scalable=no">
<style>
  html, body { margin: 0; height: 100%; background: #101214; overflow: hidden; overscroll-behavior: none; }
  #game { display: block; width: 100vw; height: 100vh; touch-action: none; }
</style>
</head>
<body>
<svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs><filter id="cf-goo"><feGaussianBlur in="SourceGraphic" stdDeviation="3"></feGaussianBlur><feColorMatrix mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 20 -8"></feColorMatrix></filter></defs></svg>
<canvas id="game"></canvas>
<script type="module">
${js}
</script>
</body>
</html>`;

writeFileSync(
  "expo/game-html.ts",
  `// GENERATED by scripts/build-expo.mjs — do not edit. Rebuild with: npm run build:expo\n` +
    `export const GAME_HTML: string = ${JSON.stringify(html)};\n`,
);
console.log(`expo/game-html.ts written (${(html.length / 1024).toFixed(0)} KB) from ${asset}`);
